{% set name = "svmbir" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40a2fcc3bdd9bbe078f922abd74ed82cb09c9b0b059e952905449b373e1927f8

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - numpy =1.21
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx]
    - pillow
    - psutil
    - python
    - numpy =1.21
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - svmbir
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - svmbir/tests/*

about:
  home: https://github.com/cabouman/svmbir
  summary: Python code for fast parallel-beam MBIR (Model Based Iterative Reconstruction)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
    - sjkisner
    - gbuzzard
    - cabouman
