{% set name = "svmbir" %}
{% set version = "0.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f73eb12d71aa35f2439fc7b3153a7c59366700951f1c665d03c8bfc6d21391bd

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - numpy =1.21
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx]
    - pillow >=9.1
    - psutil >=5.8
    - python
    - numpy =1.21
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - svmbir
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - svmbir/tests/*

about:
  home: https://github.com/cabouman/svmbir
  summary: Python code for fast parallel-beam MBIR (Model Based Iterative Reconstruction)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
    - sjkisner
    - gbuzzard
    - cabouman
