{% set name = "svmbir" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 840bbd99de28483e4d7b3642b6fc5552fd0e3954a6db5288b82840a75105d8ce

build:
  number: 0
  skip: true  # [win or py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - numpy =1.22
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx]
    - pillow >=9.1
    - psutil >=5.8
    - python
    - numpy =1.22
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - svmbir
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - svmbir/tests/*

about:
  home: https://github.com/cabouman/svmbir
  summary: Python code for fast parallel-beam MBIR (Model Based Iterative Reconstruction)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
    - sjkisner
    - gbuzzard
    - cabouman
